# name - Название базы данных для хранения
[database]
name = database.db

# token - Яндекс токен
# disk_folder - Папка на облачном диске
[yandex_data]
token = ...
disk_folder = /sync_folder

# local_folder - Папка на локальном компьютере
# buffer_size - Объем считываемой информации для хеширования
# file_size_limit - Ограничение загружаемого на диск файла
[local_data]
local_folder = Desktop/SyncFolder
buffer_size = 65536
file_size_limit = 10485760
